### PR TITLE
fix(modals): Replace focus-trap by focus-lock

### PR DESCRIPTION
**Pull request by theKashey**
Replacing _non-friendly_ to browser `focus-trap`(it emulates and focus change via onKeyDown(TAB)  handler) by _transparent_ focus-lock (observes activeElement change).

💩
- focus-lock is 1.5kb lager than focus-trap (with module concatenation enabled)
- I am not sure why smooth-ui package size grown, but I have to increase limits to pass CI

🔥
- in Safari tabs will not work as before, _ default _ Safari behavior may require you to press Option+Tab to change a focus, as long it distinguish "links" and "buttons". Now it would work as it _should_.

### CODE REVIEW

**Comment by neoziro** [comment]
@theKashey thanks for that! The PR looks completely broken, a little rebase? 🙏

**Comment by theKashey** [comment]
Not a problem

**Comment by theKashey** [comment]
Limit not 19.5
I don't know why I've got +1.5kb :(

**Comment by neoziro** [comment]
Follow up #69

**Pull request closed without merging**
